In [19]:
import yfinance as yf
import pandas as pd

In [20]:
start  = datetime(2015, 1, 1)
end    = datetime(2022, 1, 1)

In [28]:
stock_prices = yf.download('VBLAX', start=start, end=end)

daily_returns = stock_prices['Adj Close'].pct_change()
daily_price = stock_prices['Adj Close']
daily_returns['Volume'] = stock_prices['Volume']

data = pd.DataFrame({'Daily Returns': daily_returns, 'Daily Price': daily_price, 'Trading Volume': stock_prices['Volume']})
data

[*********************100%***********************]  1 of 1 completed

,Daily Returns,Daily Price,Trading Volume
Date,,,
2019-02-07 00:00:00,NaN,11.382691,0.0
2019-02-08 00:00:00,0.002225,11.408023,0.0
2019-02-11 00:00:00,-0.00222,11.382691,0.0
2019-02-12 00:00:00,-0.002226,11.357359,0.0
2019-02-13 00:00:00,-0.00223,11.332027,0.0
...,...,...,...
2021-12-28 00:00:00,-0.002546,14.967966,0.0
2021-12-29 00:00:00,-0.008296,14.843791,0.0
2021-12-30 00:00:00,0.007078,14.948861,0.0
2021-12-31 00:00:00,0.003651,15.003438,0.0
Volume,Date 2019-02-07 0 2019-02-08 0 2019-02-1...,NaN,NaN